### ISSUE TITLE
Jenkins is not started on Mac 

### ISSUE THREAD

**Issue by okamara** [zebrunner/jenkins-master#351]
Precondition:
Install docker on Mac (local env.)
Install git 

Steps:
1. git clone --recurse-submodule --branch develop https://github.com/zebrunner/zebrunner.git
2. ./zebrunner.sh  setup
3.  Open jenkins via url in browser
**Actual result:** Jenkins is not started
**Expected:** Jenkins is started

Log from jenkins-master:
2021-06-14 15:26:57.391+0000 [id=28]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading global config
jenkins.model.InvalidBuildsDir: ${ITEM_ROOTDIR}/builds does not contain ${ITEM_FULL_NAME} or ${ITEM_ROOTDIR}, cannot distinguish between projects
	at jenkins.model.Jenkins.checkRawBuildsDir(Jenkins.java:3221)
	at jenkins.model.Jenkins.loadConfig(Jenkins.java:3164)
Caused: java.io.IOException
	at jenkins.model.Jenkins.loadConfig(Jenkins.java:3167)
	at jenkins.model.Jenkins.access$1200(Jenkins.java:313)
	at jenkins.model.Jenkins$12.run(Jenkins.java:3261)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1129)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-14 15:26:57.432+0000 [id=29]	WARNING	hudson.model.Descriptor#save: Failed to save /var/jenkins_home/hudson.plugins.git.GitTool.xml
java.nio.channels.ClosedByInterruptException
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
	at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:162)
	at java.base/sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:465)
	at hudson.util.FileChannelWriter.close(FileChannelWriter.java:90)
	at hudson.util.AtomicFileWriter.close(AtomicFileWriter.java:175)
	at hudson.util.AtomicFileWriter.commit(AtomicFileWriter.java:189)
	at hudson.XmlFile.write(XmlFile.java:200)
	at hudson.model.Descriptor.save(Descriptor.java:892)
	at hudson.plugins.git.GitTool.onLoaded(GitTool.java:131)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1129)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-14 15:26:57.438+0000 [id=22]	SEVERE	hudson.util.BootFailure#publish: Failed to initialize Jenkins
jenkins.model.InvalidBuildsDir: ${ITEM_ROOTDIR}/builds does not contain ${ITEM_FULL_NAME} or ${ITEM_ROOTDIR}, cannot distinguish between projects
	at jenkins.model.Jenkins.checkRawBuildsDir(Jenkins.java:3221)
	at jenkins.model.Jenkins.loadConfig(Jenkins.java:3164)
Caused: java.io.IOException
	at jenkins.model.Jenkins.loadConfig(Jenkins.java:3167)
	at jenkins.model.Jenkins.access$1200(Jenkins.java:313)
	at jenkins.model.Jenkins$12.run(Jenkins.java:3261)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1129)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:49)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1162)
	at jenkins.model.Jenkins.<init>(Jenkins.java:960)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:295)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:312)

**Comment by vdelendik** [comment]
let's try to investigate and find a fix in 1.8.1. it supposed to be extra manual configuration step for MacOS docker

**Comment by vdelendik** [comment]
@okamara, next week please test again. who knows maybe latest jenkins is not so sensitive and we finally might support mac os.

**Comment by dhreben** [comment]
Verified on mac mini 
Docker 4.15.0
Docker engine 20.10.21
The api job worked succesfully
