### ISSUE TITLE
unable to register global variables

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-master#373]
```
Apply Zebrunner Pipeline 1.0 settings
INFRA_HOST: 18.204.139.166:80
ADMIN_EMAILS:
SONAR_URL: http://18.204.139.166:80/sonarqube
--> setting security
2022-07-25 14:41:13.218+0000 [id=39]    WARNING j.util.groovy.GroovyHookScript#execute: Failed to execute /var/jenkins_home/init.groovy.d/global-args-security.groovy
ERROR: &quot;&quot; is prohibited as a username for security reasons.
        at hudson.util.FormValidation._errorWithMarkup(FormValidation.java:269)
        at hudson.util.FormValidation.errorWithMarkup(FormValidation.java:255)
        at hudson.util.FormValidation.error(FormValidation.java:146)
        at hudson.model.User.save(User.java:806)
        at hudson.model.User.addProperty(User.java:336)
        at hudson.security.HudsonPrivateSecurityRealm.createAccount(HudsonPrivateSecurityRealm.java:513)
        at hudson.security.HudsonPrivateSecurityRealm$createAccount.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
        at global-args-security.run(global-args-security.groovy:85)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585)
        at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:139)
        at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:130)
        at jenkins.util.groovy.GroovyHookScript.run(GroovyHookScript.java:113)
        at hudson.init.impl.GroovyInitScript.init(GroovyInitScript.java:42)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:105)
        at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:181)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1159)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by vdelendik** [comment]
fixed. the similar mistakes adjusted for mcloud and selenoid sub-modules.
all of them appeared together with #372 

after the setup you can take a look to:
jenkins/variables.env
-> ADMIN_USER, ADMIN_PASS and SONAR_URL should have values!

mcloud/variables/env
-> such vars should have values:
```
STF_ROOT_GROUP_NAME=MCloud
STF_ADMIN_NAME=admin
STF_ADMIN_EMAIL=admin@zebrunner.com
```

**Comment by okamara** [comment]
Verified, fixed.
